name: Contributor Updater

on:
  workflow_dispatch:
  push:
    paths: [ content/asciidoc-pages/** ]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  check_contributors:
    name: Check Contributors
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        persist-credentials: false

    - id: files
      uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1
      if: github.event_name == 'push'
      
    - run: pip3 install bs4

    - run: |
        update_authors() {
          local file=$1
          if [[ ${file} =~ ^content/asciidoc.*.adoc ]]; then
            current_authors=$(grep ':page-authors:' "${file}" | sed -n -e 's/^.*page-authors: //p')
            contibutors=$(python3 .github/workflows/github-file-contributors.py --file "${file}")
            for contibutor in ${contibutors}; do
              if ! echo "${current_authors}" | grep "${contibutor}"; then
                echo "adding ${contibutor}"
                current_authors_replacement="${current_authors}, ${contibutor}"
                echo "${current_authors_replacement}"
                sed -i "s/${current_authors}/${current_authors_replacement}/g" "${file}"
              fi
            done
          fi
        }

        # if workflow_dispatch, then we need to get all asciidoc files
        if [[ -z "${{ steps.files.outputs.all }}" ]]; then
          for changed_file in $(find content/asciidoc-pages -name '*.adoc' -type f); do
            update_authors "${changed_file}"
          done
        else
          # shellcheck disable=2043
          for changed_file in ${{ steps.files.outputs.all }}; do
            update_authors "${changed_file}"
          done
        fi

    - uses: gr2m/create-or-update-pull-request-action@dc1726cbf4dd3ce766af4ec29cfb660e0125e8ee # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: "Update Asciidoc Contributors"
        body: "This is an automatically generated pull request, it will be automatically merged if all the CI tests pass."
        path: "content/asciidoc-pages/"
        branch: "contributor_bot"
        commit-message: "contributors: update asciidoc contributors"
        labels: automerge
        author: "adoptium-bot <adoptium-bot@eclipse.org>"
