name: Linter

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      statuses: write  # for github/super-linter/slim to mark status of each linter run

    steps:
      - name: Checkout Code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: github/super-linter/slim@454ba4482ce2cd0c505bc592e83c06e1e37ade61 # v4.10.1

        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Markdown lint complains about the issue templates
          FILTER_REGEX_EXCLUDE: .github/ISSUE_TEMPLATE/*
          VALIDATE_YAML: false
