name: Linter

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      statuses: write  # for github/super-linter/slim to mark status of each linter run

    steps:
      - name: Checkout Code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: github/super-linter/slim@985ef206aaca4d560cb9ee2af2b42ba44adc1d55 # v4.10.0

        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Markdown lint complains about the issue templates
          FILTER_REGEX_EXCLUDE: .github/ISSUE_TEMPLATE/*
          VALIDATE_YAML: false
