name: OSSF Scorecard

on:
  push:
    branches: [ main ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        persist-credentials: false
    - uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5
    - uses: github/codeql-action/upload-sarif@5b6282e01c62d02e720b81eb8a51204f527c3624 # v2.1.34
      with:
        sarif_file: results.sarif
